### ISSUE TITLE
Closing JESS doesn't close the Jekyll server

### ISSUE THREAD

**Issue by 317** [SylvainMarty/JESS#9]

**Comment by SylvainMarty** [comment]
I need to try this fix on Linux but it's working fine on OSX. All the child processes needed by the App (Jekyll Server only for the moment) are closed just before the app is stopping.

**Comment by SylvainMarty** [comment]
On Ubuntu, restarting the Jekyll Server in a same instance make the fix not working : the lastest PID is not killed when exiting the app.

<img width="695" alt="capture d ecran 2017-05-03 a 19 42 18" src="https://cloud.githubusercontent.com/assets/10723351/25673760/b5727034-3038-11e7-9a1b-92f390f1d383.png">

On OSX, this trigger an error : 

<img width="1440" alt="capture d ecran 2017-05-03 a 19 45 28" src="https://cloud.githubusercontent.com/assets/10723351/25673859/245f689e-3039-11e7-8db0-f154397faf57.png">

**Comment by SylvainMarty** [comment]
Tested on Ubuntu 16.04, the last update has corrected the problem.
